name: Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      AWS_ACCOUNT_ID: 967694737948
      ECR_REPOSITORY: devops-challenge-ecr

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Log in to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # 4. Build Docker image
      - name: Build Docker image
        run: docker build -t $ECR_REPOSITORY:latest ./images

      # 5. Tag image for ECR
      - name: Tag Docker image
        run: docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # 6. Push to ECR
      - name: Push Docker image to Amazon ECR
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
