name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      color:
        description: 'Which target group should receive traffic?'
        required: true
        default: 'blue'

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      AWS_ACCOUNT_ID: 967694737948
      ECR_REPOSITORY: devops-challenge-ecr
      DOTNET_PROJECT_PATH: src/custom-api/custom-api.csproj


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.DOTNET_PROJECT_PATH }}

      - name: Build .NET API
        run: dotnet build ${{ env.DOTNET_PROJECT_PATH }} --configuration Release --no-restore

      #TODO: Improve custom-api and develop some unit tests
      - name: Run unit tests
        run: dotnet test --no-build || echo "No tests found — skipping..."

      # Configure AWS credentials (Grants access from Github to AWS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Build Docker image (Build context is the root of the repository and points to the Dockerfile manually)
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest -f images/Dockerfile . 

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      # Set the target group based on the input color (GITHUB_ENV is used to pass variables between steps)
      - name: Set deployment color
        run: |
          echo "COLOR=${{ github.event.inputs.color || 'blue' }}" >> $GITHUB_ENV

      # Apply Terraform changes based on the selected target group
      # - name: Terraform Plan
      #   run: |
      #     echo "Planning deployment to target group: $COLOR"
      #     if [[ "$COLOR" == "green" ]]; then
      #       terraform plan -var="active_target_group=${{ secrets.TG_GREEN_ARN }}"
      #     else
      #       terraform plan -var="active_target_group=${{ secrets.TG_BLUE_ARN }}"
      #     fi

      - name: Terraform Plan (debug)
        working-directory: infra
        run: |
          export TF_LOG=DEBUG
          export TF_LOG_PATH=terraform-debug.log

          echo "Planning deployment to target group: $COLOR"

          if [[ "$COLOR" == "green" ]]; then
            terraform plan -var="active_target_group=${{ secrets.TG_GREEN_ARN }}"
          else
            terraform plan -var="active_target_group=${{ secrets.TG_BLUE_ARN }}"
          fi

      - name: Terraform Apply
        working-directory: infra
        run: |
          # Defining blue as default target group for when pushing changes
          COLOR="${{ github.event.inputs.color || 'blue' }}"
          echo "Applying deployment to target group: $COLOR"

          if [[ "$COLOR" == "green" ]]; then
            terraform apply -auto-approve -var="active_target_group=${{ secrets.TG_GREEN_ARN }}"
          else
            terraform apply -auto-approve -var="active_target_group=${{ secrets.TG_BLUE_ARN }}"
          fi

      - name: Validate deployment via health check
        run: |
          echo "Health check validation in progress..."

          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://devops-challenge-alb-1148491247.eu-west-1.elb.amazonaws.com/message)

          echo "HTTP status code: $RESPONSE"

          if [[ "$RESPONSE" -ne 200 ]]; then
            echo "Health check failed!!"
            exit 1
          fi

          echo "API is healthy and returned 200 OK."