name: Infrastructure Provisioning

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply or Destroy
        working-directory: infra
        run: |
          ACTION="${{ github.event.inputs.action }}"
          echo "Terraform action: $ACTION"

          if [[ "$ACTION" == "destroy" ]]; then
            terraform destroy -auto-approve -input=false -var-file="terraform.tfvars"
          else
            terraform apply -auto-approve -input=false -var-file="terraform.tfvars"
          fi
