name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      color:
        description: 'Which target group should receive traffic?'
        required: true
        default: 'blue'
      action:
        description: 'Terraform action (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set deployment color
        run: |
          COLOR="${{ github.event.inputs.color }}"
          if [[ -z "$COLOR" ]]; then
            COLOR="blue"
          fi
          echo "COLOR=$COLOR" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply or Destroy (Service)
        working-directory: infra
        run: |
          COLOR="${{ github.event.inputs.color }}"
          ACTION="${{ github.event.inputs.action }}"

          if [[ "$COLOR" == "blue" ]]; then
            TG_ARN="${{ secrets.TG_BLUE_ARN }}"
          else
            TG_ARN="${{ secrets.TG_GREEN_ARN }}"
          fi

          echo "Deploying service to $COLOR with TG: $TG_ARN"

          if [[ "$ACTION" == "destroy" ]]; then
            terraform destroy -auto-approve -input=false \
              -var="deployment_color=$COLOR" \
              -var="active_target_group=$TG_ARN" \
              -var-file="terraform.tfvars"
            exit 0
          fi

          terraform apply -auto-approve -input=false \
            -var="deployment_color=$COLOR" \
            -var="active_target_group=$TG_ARN" \
            -var-file="terraform.tfvars"

      - name: Wait for target group to become healthy
        run: |
          TG_ARN="${{ github.event.inputs.color == 'blue' && secrets.TG_BLUE_ARN || secrets.TG_GREEN_ARN }}"
          echo "Waiting for healthy target in $TG_ARN"

          for i in {1..30}; do
            STATE=$(aws elbv2 describe-target-health \
              --target-group-arn "$TG_ARN" \
              --query 'TargetHealthDescriptions[0].TargetHealth.State' \
              --output text)

            echo "Target state: $STATE"

            if [[ "$STATE" == "healthy" ]]; then
              echo "Target is healthy."
              exit 0
            fi

            sleep 10
          done

          echo "Timeout: Target group never became healthy"
          exit 1

      - name: Terraform Apply (Listener Switch)
        working-directory: infra
        run: |
          COLOR="${{ github.event.inputs.color }}"

          if [[ "$COLOR" == "blue" ]]; then
            TG_ARN="${{ secrets.TG_BLUE_ARN }}"
          else
            TG_ARN="${{ secrets.TG_GREEN_ARN }}"
          fi

          echo "Switching ALB listener to point to $COLOR"

          terraform apply -auto-approve -input=false \
            -var="deployment_color=$COLOR" \
            -var="active_target_group=$TG_ARN" \
            -var-file="terraform.tfvars"
