name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      color:
        description: 'Which target group should receive traffic?'
        required: true
        default: 'blue'
      action:
        description: 'Terraform action (apply or destroy)'
        required: true
        default: 'apply'
      image_tag:
        description: 'Docker image tag to deploy (e.g., SHA)'
        required: true
        default: 'latest'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "COLOR=${{ github.event.inputs.color }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV

          if [[ "${{ github.event.inputs.color }}" == "blue" ]]; then
            TG_ARN="${{ secrets.TG_BLUE_ARN }}"
          else
            TG_ARN="${{ secrets.TG_GREEN_ARN }}"
          fi

          echo "TG_ARN=$TG_ARN" >> $GITHUB_ENV
          echo "Selected target group: $TG_ARN"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply or Destroy (ECS Service only)
        working-directory: infra
        run: |
          echo "Deploying ECS service to $COLOR (TG: $TG_ARN, image: $IMAGE_TAG)"

          if [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            terraform destroy -auto-approve -input=false \
              -var="deployment_color=$COLOR" \
              -var="active_target_group=$TG_ARN" \
              -var="image_tag=$IMAGE_TAG" \
              -var-file="terraform.tfvars"
            exit 0
          fi

          terraform apply -auto-approve -input=false \
            -var="deployment_color=$COLOR" \
            -var="active_target_group=$TG_ARN" \
            -var="image_tag=$IMAGE_TAG" \
            -var-file="terraform.tfvars"

      - name: Wait for target group to become healthy
        run: |
          echo "Waiting 30s to ensure ECS task is running..."
          sleep 30

          echo "Checking health of targets in: $TG_ARN"
          for i in {1..30}; do
            STATE=$(aws elbv2 describe-target-health \
              --target-group-arn "$TG_ARN" \
              --query 'TargetHealthDescriptions[0].TargetHealth.State' \
              --output text 2>/dev/null || echo "not_found")

            if [[ "$STATE" == "healthy" ]]; then
              echo "✅ Target is healthy."
              exit 0
            elif [[ "$STATE" == "not_found" ]]; then
              echo "Target group not ready yet... retrying"
            else
              echo "🔸 Current target health state: $STATE"
            fi

            sleep 10
          done

          echo "❌ Timeout: Target group never became healthy"
          exit 1

      - name: Terraform Apply (Switch ALB Listener)
        working-directory: infra
        run: |
          echo "🔁 Switching ALB listener to point to $COLOR (TG: $TG_ARN)..."

          terraform apply -auto-approve -input=false \
            -var="deployment_color=$COLOR" \
            -var="active_target_group=$TG_ARN" \
            -var="image_tag=$IMAGE_TAG" \
            -var-file="terraform.tfvars"
